export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-2">Terms of Use</h1>
      <p className="text-sm text-slate-400 mb-8">Last updated: January 2025</p>

      <div className="space-y-8">
        {[
          { title: "1. Acceptance of Terms", body: "By creating an account or using Tweenz AI, you agree to these Terms of Use and our Privacy Policy. If you do not agree, do not use the platform." },
          { title: "2. Eligibility", body: "You must be at least 18 years old and capable of entering into binding contracts to use Tweenz AI. By using the platform you represent that you meet this requirement." },
          { title: "3. Account Responsibilities", body: "You are responsible for: (a) maintaining the confidentiality of your password; (b) all activity under your account; (c) providing accurate information. Notify us immediately if you suspect unauthorized access at support@tweenz.ae." },
          { title: "4. Acceptable Use", body: "You agree to use Tweenz AI only for lawful academic purposes. You must not: (a) use the platform to commit academic fraud or submit AI-generated content as your own without proper disclosure per your institution's rules; (b) upload materials you do not have the right to use; (c) reverse engineer, scrape, or abuse the platform; (d) share your account with others; (e) upload illegal, harmful, or offensive content." },
          { title: "5. Academic Integrity", body: "Tweenz AI is designed to help you understand, study, and prepare — not to complete your assignments for you. You are responsible for complying with your institution's academic integrity policies. The platform includes warnings when requests may conflict with standard academic integrity expectations." },
          { title: "6. Uploaded Content", body: "You retain ownership of files and content you upload. By uploading, you grant Tweenz AI a limited license to process, store, and use the content to provide the service to you. You confirm you have the right to upload and process the material for personal study purposes. We do not share your content with other users." },
          { title: "7. AI-Generated Content", body: "Content generated by AI (study packs, summaries, quiz questions, tutor answers) is for study assistance only. It may contain errors or inaccuracies. Always verify important information with primary sources and your instructors. Tweenz AI is not liable for academic consequences arising from reliance on AI-generated content." },
          { title: "8. Subscriptions and Payments", body: "Paid plans are billed through Stripe. Subscription fees are charged at the beginning of each billing period. Free trials are available per plan terms. You may cancel at any time. Refund requests are handled on a case-by-case basis; contact billing@tweenz.ae within 7 days of charge." },
          { title: "9. Termination", body: "We may suspend or terminate accounts that violate these Terms. You may delete your account at any time from Settings > Privacy and Data. On termination, your data is deleted per our Privacy Policy." },
          { title: "10. Limitation of Liability", body: "Tweenz AI is provided 'as is'. We are not liable for: (a) academic outcomes; (b) data loss; (c) service interruptions; (d) third-party integrations. Our total liability is limited to the amount you paid in the past 3 months." },
          { title: "11. Governing Law", body: "These Terms are governed by the laws of the United Arab Emirates. Disputes shall be resolved in UAE courts." },
          { title: "12. Contact", body: "For questions about these Terms: legal@tweenz.ae | Tweenz AI, United Arab Emirates" },
        ].map((s, i) => (
          <div key={i}>
            <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-2">{s.title}</h2>
            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
