-- =====================================================================
-- Prompt Orchestrator - Initial Schema
-- Multi-tenant SaaS with Row Level Security on org_id
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- ORGANIZATIONS (tenants)
-- ---------------------------------------------------------------------
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  plan text not null default 'free',
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- USERS  (mirrors auth.users; one row per app user)
-- ---------------------------------------------------------------------
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  display_name text,
  default_org_id uuid references public.organizations(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- MEMBERSHIPS  (user <-> org with role)
-- ---------------------------------------------------------------------
create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  role text not null check (role in ('owner','admin','member')) default 'member',
  created_at timestamptz not null default now(),
  unique (user_id, org_id)
);

create index if not exists memberships_user_idx on public.memberships(user_id);
create index if not exists memberships_org_idx on public.memberships(org_id);

-- ---------------------------------------------------------------------
-- TEMPLATES  (reusable prompt blueprints)
-- ---------------------------------------------------------------------
create table if not exists public.templates (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  created_by uuid references public.users(id) on delete set null,
  name text not null,
  description text,
  category text,                         -- e.g. "coding", "writing", "research"
  body jsonb not null,                   -- { sections, slots, defaults }
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists templates_org_idx on public.templates(org_id);

-- ---------------------------------------------------------------------
-- SESSIONS  (one orchestration session = raw prompt -> final prompt)
-- ---------------------------------------------------------------------
create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  raw_prompt text not null,
  intent text,                           -- detected intent label
  intent_confidence numeric,             -- 0..1
  status text not null check (status in ('intake','clarifying','ready','finalized')) default 'intake',
  target_model text,                     -- e.g. 'chatgpt' | 'claude' | 'copilot'
  template_id uuid references public.templates(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sessions_org_idx on public.sessions(org_id);
create index if not exists sessions_user_idx on public.sessions(user_id);

-- ---------------------------------------------------------------------
-- QUESTIONS  (clarification questions generated by the engine)
-- ---------------------------------------------------------------------
create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  position int not null,
  question text not null,
  rationale text,
  required boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists questions_session_idx on public.questions(session_id);

-- ---------------------------------------------------------------------
-- ANSWERS  (user answers to clarification questions)
-- ---------------------------------------------------------------------
create table if not exists public.answers (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.questions(id) on delete cascade,
  session_id uuid not null references public.sessions(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  answer text not null,
  created_at timestamptz not null default now()
);

create index if not exists answers_session_idx on public.answers(session_id);

-- ---------------------------------------------------------------------
-- PROMPT VERSIONS  (history of reconstructed prompts per session)
-- ---------------------------------------------------------------------
create table if not exists public.prompt_versions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  version int not null,
  target_model text,
  final_prompt text not null,
  rationale text,
  created_at timestamptz not null default now(),
  unique (session_id, version)
);

create index if not exists prompt_versions_session_idx on public.prompt_versions(session_id);

-- ---------------------------------------------------------------------
-- API KEYS  (for browser extension / programmatic access)
-- ---------------------------------------------------------------------
create table if not exists public.api_keys (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  key_hash text not null,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists api_keys_org_idx on public.api_keys(org_id);

-- =====================================================================
-- ROW LEVEL SECURITY
-- =====================================================================

alter table public.organizations enable row level security;
alter table public.users         enable row level security;
alter table public.memberships   enable row level security;
alter table public.templates     enable row level security;
alter table public.sessions      enable row level security;
alter table public.questions     enable row level security;
alter table public.answers       enable row level security;
alter table public.prompt_versions enable row level security;
alter table public.api_keys      enable row level security;

-- helper: is the requesting user a member of this org?
create or replace function public.is_org_member(target_org uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists(
    select 1 from public.memberships m
    where m.org_id = target_org
      and m.user_id = auth.uid()
  );
$$;

-- ---- USERS ----
drop policy if exists users_self_select on public.users;
create policy users_self_select on public.users
  for select using (id = auth.uid());

drop policy if exists users_self_update on public.users;
create policy users_self_update on public.users
  for update using (id = auth.uid());

drop policy if exists users_self_insert on public.users;
create policy users_self_insert on public.users
  for insert with check (id = auth.uid());

-- ---- ORGANIZATIONS ----
drop policy if exists orgs_member_select on public.organizations;
create policy orgs_member_select on public.organizations
  for select using (public.is_org_member(id));

drop policy if exists orgs_authenticated_insert on public.organizations;
create policy orgs_authenticated_insert on public.organizations
  for insert with check (auth.uid() is not null);

-- ---- MEMBERSHIPS ----
drop policy if exists memberships_self_select on public.memberships;
create policy memberships_self_select on public.memberships
  for select using (user_id = auth.uid() or public.is_org_member(org_id));

drop policy if exists memberships_self_insert on public.memberships;
create policy memberships_self_insert on public.memberships
  for insert with check (user_id = auth.uid());

-- ---- TEMPLATES ----
drop policy if exists templates_org_rw on public.templates;
create policy templates_org_rw on public.templates
  for all using (public.is_org_member(org_id) or is_public = true)
  with check (public.is_org_member(org_id));

-- ---- SESSIONS / QUESTIONS / ANSWERS / VERSIONS ----
drop policy if exists sessions_org_rw on public.sessions;
create policy sessions_org_rw on public.sessions
  for all using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists questions_org_rw on public.questions;
create policy questions_org_rw on public.questions
  for all using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists answers_org_rw on public.answers;
create policy answers_org_rw on public.answers
  for all using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

drop policy if exists prompt_versions_org_rw on public.prompt_versions;
create policy prompt_versions_org_rw on public.prompt_versions
  for all using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

-- ---- API KEYS ----
drop policy if exists api_keys_org_rw on public.api_keys;
create policy api_keys_org_rw on public.api_keys
  for all using (public.is_org_member(org_id))
  with check (public.is_org_member(org_id));

-- =====================================================================
-- TRIGGERS
-- =====================================================================

-- bump updated_at on session/template updates
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists trg_sessions_touch on public.sessions;
create trigger trg_sessions_touch before update on public.sessions
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_templates_touch on public.templates;
create trigger trg_templates_touch before update on public.templates
  for each row execute function public.touch_updated_at();

-- auto-create a public.users row + personal org on signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  new_org_id uuid;
  base_slug  text;
begin
  base_slug := lower(regexp_replace(split_part(new.email, '@', 1), '[^a-z0-9]+', '-', 'g'))
               || '-' || substr(new.id::text, 1, 6);

  insert into public.organizations (name, slug)
  values (split_part(new.email, '@', 1) || '''s workspace', base_slug)
  returning id into new_org_id;

  insert into public.users (id, email, display_name, default_org_id)
  values (new.id, new.email, split_part(new.email, '@', 1), new_org_id);

  insert into public.memberships (user_id, org_id, role)
  values (new.id, new_org_id, 'owner');

  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
